namespace Zinc;

public static partial class Engine
{
    public enum EventType : uint
    {
        INVALID = Internal.Sokol.sapp_event_type.SAPP_EVENTTYPE_INVALID,
        KEY_DOWN = Internal.Sokol.sapp_event_type.SAPP_EVENTTYPE_KEY_DOWN,
        KEY_UP = Internal.Sokol.sapp_event_type.SAPP_EVENTTYPE_KEY_UP,
        CHAR = Internal.Sokol.sapp_event_type.SAPP_EVENTTYPE_CHAR,
        MOUSE_DOWN = Internal.Sokol.sapp_event_type.SAPP_EVENTTYPE_MOUSE_DOWN,
        MOUSE_UP = Internal.Sokol.sapp_event_type.SAPP_EVENTTYPE_MOUSE_UP,
        MOUSE_SCROLL = Internal.Sokol.sapp_event_type.SAPP_EVENTTYPE_MOUSE_SCROLL,
        MOUSE_MOVE = Internal.Sokol.sapp_event_type.SAPP_EVENTTYPE_MOUSE_MOVE,
        MOUSE_ENTER = Internal.Sokol.sapp_event_type.SAPP_EVENTTYPE_MOUSE_ENTER,
        MOUSE_LEAVE = Internal.Sokol.sapp_event_type.SAPP_EVENTTYPE_MOUSE_LEAVE,
        TOUCHES_BEGAN = Internal.Sokol.sapp_event_type.SAPP_EVENTTYPE_TOUCHES_BEGAN,
        TOUCHES_MOVED = Internal.Sokol.sapp_event_type.SAPP_EVENTTYPE_TOUCHES_MOVED,
        TOUCHES_ENDED = Internal.Sokol.sapp_event_type.SAPP_EVENTTYPE_TOUCHES_ENDED,
        TOUCHES_CANCELLED = Internal.Sokol.sapp_event_type.SAPP_EVENTTYPE_TOUCHES_CANCELLED,
        RESIZED = Internal.Sokol.sapp_event_type.SAPP_EVENTTYPE_RESIZED,
        ICONIFIED = Internal.Sokol.sapp_event_type.SAPP_EVENTTYPE_ICONIFIED,
        RESTORED = Internal.Sokol.sapp_event_type.SAPP_EVENTTYPE_RESTORED,
        FOCUSED = Internal.Sokol.sapp_event_type.SAPP_EVENTTYPE_FOCUSED,
        UNFOCUSED = Internal.Sokol.sapp_event_type.SAPP_EVENTTYPE_UNFOCUSED,
        SUSPENDED = Internal.Sokol.sapp_event_type.SAPP_EVENTTYPE_SUSPENDED,
        RESUMED = Internal.Sokol.sapp_event_type.SAPP_EVENTTYPE_RESUMED,
        QUIT_REQUESTED = Internal.Sokol.sapp_event_type.SAPP_EVENTTYPE_QUIT_REQUESTED,
        CLIPBOARD_PASTED = Internal.Sokol.sapp_event_type.SAPP_EVENTTYPE_CLIPBOARD_PASTED,
        FILES_DROPPED = Internal.Sokol.sapp_event_type.SAPP_EVENTTYPE_FILES_DROPPED,
        NUM = Internal.Sokol.sapp_event_type._SAPP_EVENTTYPE_NUM,
        FORCE_U32 = Internal.Sokol.sapp_event_type._SAPP_EVENTTYPE_FORCE_U32,
    }
}

public enum Key : uint
{
    INVALID = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_INVALID,
    SPACE = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_SPACE,
    APOSTROPHE = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_APOSTROPHE,
    COMMA = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_COMMA,
    MINUS = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_MINUS,
    PERIOD = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_PERIOD,
    SLASH = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_SLASH,
    Num0 = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_0,
    Num1 = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_1,
    Num2 = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_2,
    Num3 = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_3,
    Num4 = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_4,
    Num5 = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_5,
    Num6 = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_6,
    Num7 = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_7,
    Num8 = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_8,
    Num9 = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_9,
    SEMICOLON = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_SEMICOLON,
    EQUAL = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_EQUAL,
    A = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_A,
    B = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_B,
    C = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_C,
    D = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_D,
    E = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_E,
    F = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_F,
    G = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_G,
    H = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_H,
    I = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_I,
    J = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_J,
    K = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_K,
    L = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_L,
    M = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_M,
    N = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_N,
    O = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_O,
    P = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_P,
    Q = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_Q,
    R = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_R,
    S = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_S,
    T = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_T,
    U = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_U,
    V = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_V,
    W = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_W,
    X = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_X,
    Y = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_Y,
    Z = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_Z,
    LEFT_BRACKET = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_LEFT_BRACKET,
    BACKSLASH = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_BACKSLASH,
    RIGHT_BRACKET = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_RIGHT_BRACKET,
    GRAVE_ACCENT = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_GRAVE_ACCENT,
    WORLD_1 = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_WORLD_1,
    WORLD_2 = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_WORLD_2,
    ESCAPE = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_ESCAPE,
    ENTER = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_ENTER,
    TAB = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_TAB,
    BACKSPACE = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_BACKSPACE,
    INSERT = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_INSERT,
    DELETE = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_DELETE,
    RIGHT = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_RIGHT,
    LEFT = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_LEFT,
    DOWN = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_DOWN,
    UP = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_UP,
    PAGE_UP = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_PAGE_UP,
    PAGE_DOWN = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_PAGE_DOWN,
    HOME = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_HOME,
    END = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_END,
    CAPS_LOCK = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_CAPS_LOCK,
    SCROLL_LOCK = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_SCROLL_LOCK,
    NUM_LOCK = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_NUM_LOCK,
    PRINT_SCREEN = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_PRINT_SCREEN,
    PAUSE = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_PAUSE,
    F1 = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_F1,
    F2 = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_F2,
    F3 = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_F3,
    F4 = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_F4,
    F5 = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_F5,
    F6 = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_F6,
    F7 = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_F7,
    F8 = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_F8,
    F9 = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_F9,
    F10 = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_F10,
    F11 = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_F11,
    F12 = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_F12,
    F13 = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_F13,
    F14 = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_F14,
    F15 = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_F15,
    F16 = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_F16,
    F17 = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_F17,
    F18 = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_F18,
    F19 = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_F19,
    F20 = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_F20,
    F21 = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_F21,
    F22 = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_F22,
    F23 = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_F23,
    F24 = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_F24,
    F25 = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_F25,
    KP_0 = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_KP_0,
    KP_1 = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_KP_1,
    KP_2 = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_KP_2,
    KP_3 = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_KP_3,
    KP_4 = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_KP_4,
    KP_5 = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_KP_5,
    KP_6 = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_KP_6,
    KP_7 = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_KP_7,
    KP_8 = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_KP_8,
    KP_9 = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_KP_9,
    KP_DECIMAL = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_KP_DECIMAL,
    KP_DIVIDE = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_KP_DIVIDE,
    KP_MULTIPLY = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_KP_MULTIPLY,
    KP_SUBTRACT = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_KP_SUBTRACT,
    KP_ADD = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_KP_ADD,
    KP_ENTER = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_KP_ENTER,
    KP_EQUAL = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_KP_EQUAL,
    LEFT_SHIFT = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_LEFT_SHIFT,
    LEFT_CONTROL = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_LEFT_CONTROL,
    LEFT_ALT = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_LEFT_ALT,
    LEFT_SUPER = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_LEFT_SUPER,
    RIGHT_SHIFT = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_RIGHT_SHIFT,
    RIGHT_CONTROL = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_RIGHT_CONTROL,
    RIGHT_ALT = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_RIGHT_ALT,
    RIGHT_SUPER = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_RIGHT_SUPER,
    MENU = Internal.Sokol.sapp_keycode.SAPP_KEYCODE_MENU,
}

public enum Modifiers : uint
{
    SHIFT = Internal.Sokol.App.SAPP_MODIFIER_SHIFT,
    CTRL = Internal.Sokol.App.SAPP_MODIFIER_CTRL,
    ALT = Internal.Sokol.App.SAPP_MODIFIER_ALT,
    SUPER = Internal.Sokol.App.SAPP_MODIFIER_SUPER,
    LMB = Internal.Sokol.App.SAPP_MODIFIER_LMB,
    RMB = Internal.Sokol.App.SAPP_MODIFIER_RMB,
    MMB = Internal.Sokol.App.SAPP_MODIFIER_MMB
}
    
public enum MouseButton : uint
{
    LEFT = Internal.Sokol.sapp_mousebutton.SAPP_MOUSEBUTTON_LEFT,
    RIGHT = Internal.Sokol.sapp_mousebutton.SAPP_MOUSEBUTTON_RIGHT,
    MIDDLE = Internal.Sokol.sapp_mousebutton.SAPP_MOUSEBUTTON_MIDDLE,
    INVALID = Internal.Sokol.sapp_mousebutton.SAPP_MOUSEBUTTON_INVALID
}